name: Check Saltstack
on:
  push
jobs:
  linting:
    name: 'Lint Saltstack'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Run salt-lint
        uses: roaldnefs/salt-lint-action@master
        env:
          ACTION_STATE_FIND_PATTERN: '^.*\.(sls|jinja|j2|tmpl|tst)$'
          ACTION_STATE_FIND_TYPE: 'regex'